on: [push]

jobs:
  trigger-buildkite:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a Buildkite Build
        uses: "buildkite/trigger-pipeline-action@v2.4.1"
        with:
          buildkite_api_access_token: ${{ secrets.BK_WRITE_BUILD }}
          pipeline: "mstoney-onboard-training/gh-trigger"
          branch: ${{ github.ref_name }}
          commit: ${{ github.sha }}
          message: ":github: Triggered from a GitHub Action"
          build_env_vars: '{"TRIGGERED_FROM_GHA": "true"}'
          build_meta_data: '{"FOO": "bar"}'
          ignore_pipeline_branch_filter: true
          send_pull_request: true
          wait: true
          wait_interval: 10
          wait_timeout: 300
